### PR TITLE
Merge workflow into single file + add ruby 3.0

### PR DESCRIPTION
**Pull request by CAMOBAP**
- relaton/relaton-data-iho#13 - wrong configuration need to be fixed
 - relaton/relaton-data-bipm#13 - wrong configuration need to be fixed
 - relaton/relaton-iho#12 
 - relaton/relaton-ieee#6 
 - relaton/relaton-iev#14 
 - relaton/relaton-bipm#10 
 - relaton/relaton-ecma#3 
 - relaton/relaton-calconnect#9 
 - relaton/relaton-ogc#15 
 - relaton/relaton-nist#52 
 - relaton/relaton-ietf#45 
 - relaton/relaton-itu#54 
 - relaton/relaton#84 
 - relaton/relaton-cli#95 
 - relaton/relaton-gb#36 
 - relaton/relaton-un#7 
 - relaton/relaton-iec#38 
 - relaton/relaton-omg#4 
 - relaton/relaton-iso#97 
 - relaton/relaton-iso-bib#14 
 - relaton/relaton-bib#41

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@andrew2net @ronaldtse I propose to discuss all concerns about CI update here.

My primary motivation was to add ruby 3.0 to test matrice. But also I propagated all practices which we are used in metanorma currently. Also, I have added all repositories to cimas.yml so now it's up to date

As @andrew2net noted in https://github.com/relaton/relaton-iso-bib/pull/14#pullrequestreview-609238212 I'm also not 100% happy about a redundant CI execution on re-runs, but I think it worth it because CI configuration becomes more clear, and also GH Actions Team promised to resolve this

@andrew2net let me know if you agree/disagree with this, and I will proceed with PR merging

**Comment by andrew2net** [comment]
@CAMOBAP as I said here relaton/relaton-iso-bib#14 I had a negative experience with many builds in one file. Maybe it has changed since when and such a problem will never happen again. We need to test this configuration on 1-2 repositories before spread it on all others. In another case, we could stick to rebuilding from time to time.
I've noticed I got the rebuilding issue about 6 pm CET and later. Looks like at the time when US users start testing their projects which overload GH actions service.

**Comment by CAMOBAP** [comment]
@andrew2net maybe you can show some links to runs which are failed?

**Comment by andrew2net** [comment]
@CAMOBAP please see [here](https://github.com/interscript/interscript/commits/master/.github/workflows/test.yml) Commits on May 5, 2020.
I spent more than an hour trying to rerun GH action that day. The error happened at the begginig of step "Update gems" in the bundle install command. I've rerun the action many times and got one or more OS / Ruby version fails. Unfortunately, GitHub doesn't save logs for so long.
It occurred with other repos but they have separated configs and 1-2 reruns solve the issue. But I don't remember if there were such issues last time, so maybe GH has fixed this issue.
I suggesting test the new configuration on one or two repos. Let's try to rerun builds several times at 6-8 pm CET.

**Comment by CAMOBAP** [comment]
@andrew2net got you, could you please choose 1-2 repos that change more often, and merge PRs there.

I'm asking you because I'm not very familiar with relaton's gems

**Comment by andrew2net** [comment]
@CAMOBAP ok, I'll do it tonight.

**Comment by andrew2net** [comment]
@CAMOBAP I've tried to rerun actions in relaton-bib and relaton-iso several times. Looks like GH fixes the issue with updating gems.
So we can use the configuration except the Ruby 3.0. Not all the gems can work on Ruby 3.0. For example, the bibtex gem raises an error.

**Comment by CAMOBAP** [comment]
@andrew2net, as you may see, 3.0 support is experimental, even it failed for 3.0, you will still get a green label on CI. I understand that probably we cannot fix all issues related to 3.0 but should anyway move in this direction, @ronaldtse correct me if I'm wrong

**Comment by ronaldtse** [comment]
> probably we cannot fix all issues related to 3.0 but should anyway move in this direction

@CAMOBAP is correct, thanks!

**Comment by CAMOBAP** [comment]
Ok, I'm going to merge all related PRs then

**Pull request merged**
